# Generated by Django 3.1.5 on 2021-09-24 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('main_image', models.ImageField(default='null', upload_to='static/uploads/images')),
                ('image_1', models.ImageField(default='null', upload_to='static/uploads/images')),
                ('image_2', models.ImageField(default='null', upload_to='static/uploads/images')),
                ('image_3', models.ImageField(default='null', upload_to='static/uploads/images')),
                ('image_4', models.ImageField(default='null', upload_to='static/uploads/images')),
                ('image_5', models.ImageField(default='null', upload_to='static/uploads/images')),
                ('image_6', models.ImageField(default='null', upload_to='static/uploads/images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitechen_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
