# Generated by Django 3.1.5 on 2021-10-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_type',
            field=models.CharField(choices=[('kitchen', 'kitchen'), ('furniture', 'furniture')], default='', max_length=20),
        ),
    ]
