# Generated by Django 3.1.5 on 2021-10-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0007_auto_20211005_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(default='null', upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.ImageField(default='null', upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=models.ImageField(default='null', upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_4',
            field=models.ImageField(default='null', upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_5',
            field=models.ImageField(default='null', upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_6',
            field=models.ImageField(default='null', upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(default='null', upload_to='media/uploads/images'),
        ),
    ]
