# Generated by Django 3.1.5 on 2021-10-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0008_auto_20211006_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(default='null', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.ImageField(default='null', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=models.ImageField(default='null', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_4',
            field=models.ImageField(default='null', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_5',
            field=models.ImageField(default='null', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_6',
            field=models.ImageField(default='null', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(default='null', upload_to='uploads/images'),
        ),
    ]
