# Generated by Django 3.1.5 on 2021-10-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0009_auto_20211013_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(default='null', upload_to='uploads'),
        ),
    ]
